### PR TITLE
Replace passport-github with passport-github2.

### PR DESCRIPTION
**Pull request by vokal-isaac**
@jrit Making this change locally appears to resolve the issue.

### CODE REVIEW

**Comment by foresmac** [comment]
Does this address why CVR is failing on upload?

**Comment by vokal-isaac** [comment]
Oh, I suppose I should have been more specific about "the issue" I think this resolves—for me locally, this change allows me to log in to the web interface.  I haven't tried a local upload of coverage to see what happens.

**Comment by foresmac** [comment]
💋 💋 💋 💋 @scottferg 💋 💋 💋 💋

**Comment by jrit** [comment]
yeah, this sounds about right, thanks

**Comment by jrit** [comment]
We need to bump package.json, publish to npm, and then run a new deploy on our own server to actually update. Alright if I do that all tomorrow?

**Comment by vokal-isaac** [comment]
:+1: fine with me. I could bump the version number, but I'm not sure I can publish or do the deploying, so I'm happy to leave it to you. 

As I realized from Chris's comment, I'm not sure if this fixes everything, but I do think it fixes login.

**Comment by jrit** [comment]
OK, I didn't get to it yesterday, so this weekend

**Pull request merged**
